[package]
name = "facet-json"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/facet-json"
description = "JSON serialization and deserialization for Shapely types"
keywords = ["json", "serialization", "deserialization", "reflection", "facet"]
categories = ["encoding", "parsing", "data-structures"]
rust-version.workspace = true

[dependencies]
log = "0.4.27"
facet-trait = { workspace = true }
facet-poke = { version = "0.1.0", path = "../facet-poke" }

[dev-dependencies]
color-backtrace = { version = "0.7.0", default-features = false, features = [
    "use-btparse-crate",
] }
ctor = "0.4.1"
facet-derive.workspace = true
