[package]
name = "shapely-json"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/shapely-json"
description = "A serialization and deserialization library for JSON"
keywords = ["json", "serialization", "deserialization"]
categories = ["encoding", "parsing"]
rust-version.workspace = true

[dependencies]
jiter = { version = "0.8.2", default-features = false }
log = "0.4.26"
shapely = { version = "0.1.0", path = "../shapely" }

[dev-dependencies]
test-log = "0.2.17"
