[workspace]
members = ["shapely", "shapely-derive", "shapely-json"]
resolver = "3"

[workspace.package]
version = "0.1.0-alpha.1"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/shapely"
homepage = "https://github.com/bearcove/shapely"
documentation = "https://docs.rs/shapely"
description = "Know the shape of your types"
keywords = ["serialization", "deserialization"]
categories = ["encoding", "parsing"]

[workspace.dependencies]
shapely = { version = "0.1.0-alpha.1", path = "shapely" }
shapely-derive = { version = "0.1.0-alpha.1", path = "shapely-derive" }
shapely-json = { version = "0.1.0-alpha.1", path = "shapely-json" }
