[workspace]
members = [
    "facet",
    "facet-codegen",
    "facet-trait",
    "facet-derive",
    "facet-json",
    "facet-opaque",
    "facet-peek",
    "facet-poke",
    "facet-spez",
    "facet-types",
    "facet-samplelibc",
]
resolver = "3"

[workspace.package]
version = "3.1.1"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/facet-rs/facet"
homepage = "https://github.com/facet-rs/facet"
documentation = "https://docs.rs/facet"
description = "One trait for reflection, serialization, deserialization"
keywords = [
    "serialization",
    "deserialization",
    "reflection",
    "schema",
    "validation",
]
categories = ["encoding", "parsing", "development-tools", "data-structures"]

[workspace.dependencies]
facet-trait = { version = "3.1.1", path = "facet-trait" }
facet-derive = { version = "3.1.1", path = "facet-derive" }
unsynn = "0.0.25"
