[workspace]
members = [
    "facet",
    "facet-codegen",
    "facet-trait",
    "facet-derive",
    "facet-json",
    "facet-opaque",
    "facet-peek",
    "facet-poke",
    "facet-spez",
    "facet-types",
    "facet-samplelibc",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.86.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/facet-rs/facet"

[workspace.dependencies]
facet-trait = { version = "0.1.0", path = "facet-trait" }
facet-derive = { version = "0.1.0", path = "facet-derive" }
unsynn = "0.0.25"
