[package]
name = "facet"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Re-exports the Facet trait and derive macros, along with Shape and all related types"
keywords = ["facet", "trait", "derive", "shape", "introspection", "reflection"]
categories = ["development-tools"]

[dependencies]
facet-trait.workspace = true
facet-derive.workspace = true

[features]
# Does nothing, only used for tests
testfeat = []

[dev-dependencies]
facet-spez = { path = "../facet-spez" }
