[package]
name = "facet-codegen"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Code generation utilities for Facet"
keywords = ["code-generation", "templates"]
categories = ["development-tools"]

[dependencies]
minijinja = { version = "2.9.0", default-features = false, features = [
    "builtins",
] }
similar = { version = "2.4.0", features = ["inline"] }
