[package]
name = "facet-trait"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Core types and traits for the facet ecosystem, providing fundamental reflection capabilities"
keywords = ["reflection", "introspection", "serialization", "deserialization"]
categories = ["development-tools", "encoding"]

[dependencies]
facet-opaque = { version = "3.1.1", path = "../facet-opaque" }
facet-spez = { version = "3.1.1", path = "../facet-spez" }
facet-types = { version = "0.1.0", path = "../facet-types" }
