[package]
name = "shapely-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Proc macro for deriving the 'Schematic' trait in shapely"
keywords = [
  "reflection",
  "introspection",
  "serialization",
  "deserialization",
  "derive",
]
categories = ["development-tools", "encoding"]

[lib]
proc-macro = true

[dependencies]
unsynn = "0.0.25"
