[package]
name = "facet-pretty"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Pretty-printing for types implementing the Shapely trait"
keywords = [
    "pretty-print",
    "formatting",
    "reflection",
    "serialization",
    "visualization",
]
categories = ["development-tools", "visualization", "command-line-utilities"]

[dependencies]
facet-trait = { workspace = true }

[dev-dependencies]
facet = { workspace = true }
