[package]
name = "facet-args"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
facet-poke.workspace = true
facet-trait.workspace = true
log = "0.4.27"

[dev-dependencies]
facet.workspace = true
facet-pretty = { path = "../facet-pretty" }
