[package]
name = "facet-poke"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
facet-peek = { version = "0.1.0", path = "../facet-peek" }
facet-trait.workspace = true

[dev-dependencies]
color-backtrace = { version = "0.7.0", default-features = false, features = [
    "use-btparse-crate",
] }
ctor = "0.4.1"
owo-colors = "4.2.0"
facet-derive.workspace = true
facet-samplelibc = { path = "../facet-samplelibc" }
