[package]
name = "shapely"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
shapely-trait.workspace = true
shapely-derive.workspace = true

[dev-dependencies]
color-backtrace = { version = "0.7.0", default-features = false, features = [
    "use-btparse-crate",
] }
cargo-husky = { version = "1", default-features = false, features = [
    "user-hooks",
] }
ctor = "0.4.1"
owo-colors = "4.2.0"

[features]
# Does nothing, only used for tests
testfeat = []
