[package]
name = "shapely"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
shapely-trait.workspace = true
shapely-derive.workspace = true

[features]
# Does nothing, only used for tests
testfeat = []

[dev-dependencies]
shapely-spez = { path = "../shapely-spez" }
