[package]
name = "shapely"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
shapely-derive = { path = "../shapely-derive", optional = true }

[features]
default = ["derive"]
derive = ["shapely-derive"]
