name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    merge_group:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup cargo cache
              uses: Swatinem/rust-cache@v2

            - name: Install Rust specified toolchain
              run: |
                  rustc --version

            - name: Install just and cargo-nextest
              uses: taiki-e/install-action@v2
              with:
                  tool: just,cargo-nextest

            - name: Run tests
              shell: bash
              run: |
                  just ci
