name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    merge_group:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Cache cargo registry, index, and build artifacts
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cargo-

            # Install the toolchain specified in rust-toolchain.toml
            # and components needed for default checks/formatting.
            - name: Install default toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                # Use the toolchain specified in rust-toolchain.toml
                # Components specified here are added to the ones in the file
                components: rustfmt, clippy

            # Install the specific nightly toolchain needed for Miri
            - name: Install nightly toolchain for Miri
              uses: dtolnay/rust-toolchain@stable
              with:
                toolchain: nightly-2025-02-17
                components: miri, rust-src

            - name: Install just and cargo-nextest
              uses: taiki-e/install-action@v2
              with:
                  tool: just,cargo-nextest

            - name: Run tests
              shell: bash
              run: |
                  just ci
