name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    merge_group:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Cache cargo registry, index, and build artifacts
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cargo-

            - name: Install tools
              uses: taiki-e/install-action@v2
              with:
                  tool: cargo-hack,just,cargo-nextest
            - name: Run tests
              shell: bash
              run: |
                  just ci
