name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    merge_group:

jobs:
    test:
        strategy:
            matrix:
                os: [namespace-profile-macos-arm64, namespace-profile-linux-amd64]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: miri, rust-src, rustfmt, clippy

            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Setup cargo cache
              uses: namespacelabs/nscloud-cache-action@v1
              with:
                  cache: |
                      rust
            - name: Install Rust specified toolchain
              run: |
                  rustc --version
            - name: Install just and cargo-nextest
              uses: taiki-e/install-action@v2
              with:
                  tool: just,cargo-nextest

            - name: Run tests
              shell: bash
              run: |
                  just ci
