name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust specified toolchain
        run: |
          rustc --version

      - name: Install just and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest

      - name: Run tests
        shell: bash
        run: |
          just

  miri:
    runs-on: self-hosted-unknown-linux-gnu-x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Setup cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run miri
        run: just miri
